// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4bf8misFSsmRkwBRMYJLsUsU4GCeLUIo',
    appId: '1:200565662739:web:b88d04fd79f57a23ea8be6',
    messagingSenderId: '200565662739',
    projectId: 'peerprep-868cb',
    authDomain: 'peerprep-868cb.firebaseapp.com',
    storageBucket: 'peerprep-868cb.appspot.com',
    measurementId: 'G-VV1RFLCKEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtBUK2VlF-b8J5rz9Btzu9JbsnM6ldqw',
    appId: '1:200565662739:android:70c99c3b8a90b9feea8be6',
    messagingSenderId: '200565662739',
    projectId: 'peerprep-868cb',
    storageBucket: 'peerprep-868cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvK7o6uVb5fpWKDs8xD8T7hESPVSRjYZo',
    appId: '1:200565662739:ios:ed5b8a7849ec2e64ea8be6',
    messagingSenderId: '200565662739',
    projectId: 'peerprep-868cb',
    storageBucket: 'peerprep-868cb.appspot.com',
    iosBundleId: 'com.example.peerprep2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvK7o6uVb5fpWKDs8xD8T7hESPVSRjYZo',
    appId: '1:200565662739:ios:272bfd087d3df0d1ea8be6',
    messagingSenderId: '200565662739',
    projectId: 'peerprep-868cb',
    storageBucket: 'peerprep-868cb.appspot.com',
    iosBundleId: 'com.example.peerprep2.RunnerTests',
  );
}
